// app
export const SET_APP_VERSION = 'SET_APP_VERSION'
// locale
export const SET_LOCALE = 'SET_LOCALE'
// error
export const SHOW_ERROR = 'SHOW_ERROR'
export const ERROR = 'ERROR'
// success
export const SHOW_SUCCESS = 'SHOW_SUCCESS'
export const SUCCESS = 'SUCCESS'
// loading
export const SHOW_LOADING = 'SHOW_LOADING'
// auth
export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USER = 'SAVE_USER'
export const LOGOUT = 'LOGOUT'
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED'
export const RESET_EMAIL_SENT = 'RESET_EMAIL_SENT'
export const SHOW_CHANGE_PASSWORD_INPUTS = 'SHOW_CHANGE_PASSWORD_INPUTS'
// profile
export const FILL_PROFILE = 'FILL_PROFILE'
export const ADD_PROFILE_DATA = 'ADD_PROFILE_DATA'
// Admin - Users
export const USERS = 'USERS'
export const TOTAL_USERS = 'TOTAL_USERS'
// Friends
export const FRIENDS = 'FRIENDS'
export const SENT_FRIEND_REQUESTS = 'SENT_FRIEND_REQUESTS'
export const RECEIVED_FRIEND_REQUESTS = 'RECEIVED_FRIEND_REQUESTS'
export const ADD_SENT_FRIEND_REQUEST = 'ADD_SENT_FRIEND_REQUEST'
export const REMOVE_SENT_FRIEND_REQUEST = 'REMOVE_SENT_FRIEND_REQUEST'
export const REMOVE_RECEIVED_FRIEND_REQUEST = 'REMOVE_RECEIVED_FRIEND_REQUEST'
export const REMOVE_FRIEND = 'REMOVE_FRIEND'
export const UPDATE_FRIEND = 'UPDATE_FRIEND'
